ng-doc/ng-doc

libs/app/components/navbar/navbar.component.scss, libs/app/components/root/root.component.scss, libs/app/ng-package.json, libs/app/services/sidebar/sidebar.service.ts, libs/app/styles/variables.scss, libs/ui-kit/animations/fade.ts, libs/ui-kit/components/dropdown/dropdown.component.ts, libs/ui-kit/components/label/label.component.ts, libs/ui-kit/ng-package.json, libs/ui-kit/styles/mixins.scss
Here are some enhancements:
- Header has glass effect
- Document scrolling is blocked when the sidebar is opened (mobile view)
=> Add glass effect to the header

apps/ng-doc/src/app/pages/docs/getting-started/installation/index.md
-   [ ] The commit message follows our guidelines: https://github.com/skoropadas/ng-doc/blob/main/CONTRIBUTING.md#commit
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)
-   [ ] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, local variables)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] CI related changes
-   [x] Documentation content changes
-   [ ] Other... Please describe:
-   [ ] Yes
-   [x] No
=> Update installation docs

apps/ng-doc/src/app/pages/docs/getting-started/installation/index.md
-   [ ] The commit message follows our guidelines: https://github.com/skoropadas/ng-doc/blob/main/CONTRIBUTING.md#commit
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)
-   [ ] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, local variables)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] CI related changes
-   [ ] Documentation content changes
-   [ ] Other... Please describe:
-   [ ] Yes
-   [ ] No
=> docs(getting-started): update installation docs (#50)

libs/builder/engine/builder.ts, libs/builder/engine/entity-life-cycle.ts, libs/builder/helpers/index.ts, libs/builder/helpers/print-progress.ts, libs/builder/operators/index.ts, libs/builder/operators/progress.ts
NgDoc does not output the current progress to the console
NgDoc does output the current progress to the console
-   [ ] Yes
-   [X] No
=> feat(builder): the current state of the build is now displayed in the console

apps/ng-doc/docs/guides/playground/index.md, apps/ng-doc/docs/guides/playground/ng-doc.page.ts, libs/app/components/playground/base-playground.ts, libs/app/components/playground/playground-demo/playground-demo.component.html, libs/app/components/playground/playground-demo/playground-demo.component.ts, libs/app/components/playground/playground-properties/playground-properties.component.html, libs/app/components/playground/playground-properties/playground-properties.component.scss, libs/app/components/playground/playground-properties/playground-properties.component.ts, libs/app/components/playground/playground.component.html, libs/app/components/playground/playground.component.ts, libs/app/interfaces/processor-options.ts, libs/app/processors/html-processor/html-processor.directive.ts, libs/app/processors/playground-processor/playground-processor.directive.ts, libs/builder/engine/actions.ts, libs/builder/engine/actions/playground.action.ts, libs/builder/engine/entities/page.entity.ts, libs/builder/templates/playgrounds.ts.nunj, libs/core/helpers/index.ts, libs/core/helpers/stringify.ts, libs/core/interfaces/index.ts, libs/core/interfaces/playground-config.ts, libs/core/interfaces/playground-options.ts, libs/ui-kit/components/blockquote/blockquote.component.scss, libs/ui-kit/components/button/button.component.scss, libs/ui-kit/components/smooth-resize/smooth-resize.component.ts
…aking them more dynamic and reusable
This PR adds more opportunities to configure playgrounds, making them more dynamic and reusable.
=> [Feat] add more opportunities to configure playgrounds

apps/ng-doc/docs/features/keywords/index.md
path is not used anymore, it is replaced by 'url' and we can provide more options
=> fix documentation concerning Global Keyword

apps/ng-doc/docs/features/keywords/index.md, apps/ng-doc/docs/ng-doc.api.ts, libs/app/components/page-link/page-link.component.html, libs/app/components/page-link/page-link.component.ts, libs/utils/html/plugins/keywords.plugin.ts
=> feat(builder): add support for query parameters for the keywords

libs/builder/schematics/category/schema.json, libs/builder/schematics/page/schema.json
Docs already exist. This PR just adds the missed `name` properties in schemas.
=> fix(builder): add missed name options in schemas

apps/ng-doc/docs/getting-started/installation/index.md
=> docs(app): fix builder name in installation documentation

apps/ng-doc/project.json, libs/builder/dev-server/index.ts, libs/builder/dev-server/patch-builder-context.ts
=> fix(builder): eliminate dev-server schema validation error

libs/app/components/api-list/api-list.component.html, libs/app/components/api-list/api-list.component.ts, libs/builder/schematics/api/files/ng-doc.api.ts.template, libs/builder/templates/api-list.ts.nunj
=> fix: allows customizing the title of the API page

libs/add/schematics/ng-add/constants/assets.ts, libs/add/schematics/ng-add/steps/add-assets.ts, libs/add/schematics/ng-add/steps/add-tsconfig-paths.ts, libs/add/schematics/ng-add/testing/ng-add-module-app.spec.ts, libs/add/schematics/ng-add/testing/ng-add-standalone-app.spec.ts, libs/add/schematics/ng-add/utils/get-project-name.ts, libs/add/schematics/ng-add/utils/get-project.ts
Somewhat related to the following issue.
Issue Number: #115 
See below [comment](https://github.com/ng-doc/ng-doc/pull/160#issuecomment-2156037058) for more information.
=> fix(ng-add): undefined project in assets and tsconfig paths

apps/ng-doc/docs/writing-content/keywords/loaders.md, apps/ng-doc/ng-doc.config.ts, libs/keywords-loaders/index.ts, libs/keywords-loaders/rxjs/helpers/fetch-docs.ts, libs/keywords-loaders/rxjs/helpers/get-api-url.ts, libs/keywords-loaders/rxjs/helpers/get-rxjs-host.ts, libs/keywords-loaders/rxjs/helpers/index.ts, libs/keywords-loaders/rxjs/helpers/rxjs-to-keyword.ts, libs/keywords-loaders/rxjs/index.ts, libs/keywords-loaders/rxjs/interfaces/index.ts, libs/keywords-loaders/rxjs/interfaces/rxjs-page.ts, libs/keywords-loaders/rxjs/rxjs-keywords-loader.ts, libs/keywords-loaders/rxjs/types/index.ts, libs/keywords-loaders/rxjs/types/rxjs-response.ts, libs/keywords-loaders/rxjs/types/rxjs-version.ts
In my project, I've been creating different classes/interfaces that work with rxjs types, so I created rxjs keywords loader. I think it might be useful for other users of this great library, so I decided to share my code with the rest :)
=> feat(keywords-loader): add rxjs keywords loader

libs/keywords-loaders/angular/helpers/fetch-docs.ts, libs/keywords-loaders/angular/interfaces/index.ts, libs/keywords-loaders/angular/interfaces/ng-response.ts, libs/keywords-loaders/angular/ng-keywords-loader.ts, libs/keywords-loaders/angular/types/index.ts, libs/keywords-loaders/angular/types/ng-response.ts
Resolves #210
Issue Number: #210
=> fix(keywords-loader): adjust ng-keywords-loader to different api manifest structure

apps/ng-doc/docs/writing-content/keywords/index.md
=> docs(keyword): update keyword creation on pages

libs/app/components/page-link/page-link.component.ts
Resolves #216
Issue Number: #216
=> fix(app): resolving properly anchor links when using base-href

apps/ng-doc/docs/getting-started/configuration/index.md
'pages' does not exist anymore, docsPath seems to be the new property
=> Update Configuration page

CONTRIBUTING.md, libs/builder/package.json, package-lock.json, package.json
fix #222
Issue Number: #222 
Tested manually, and no error found
=> Update @parcel/watcher version

libs/app/styles/js-doc.scss, libs/builder/templates/api/function-declaration.html.nunj, libs/builder/templates/helpers/method.html.nunj, libs/builder/templates/helpers/overload.html.nunj
Issue Number: Resolves #219 
I've also added return type section in function declaration
=> feat(builder): add support for `@returns` tag

apps/ng-doc/docs/api-documentation/documenting-declarations/index.md, libs/app/components/page-link/page-link.component.ts, libs/app/styles/page.scss, libs/builder/engine/nunjucks/actions/api.action.ts, libs/builder/templates/api/base.html.nunj, libs/builder/templates/helpers/accessor.html.nunj, libs/builder/templates/helpers/method.html.nunj, libs/builder/templates/helpers/overload.html.nunj, libs/builder/templates/helpers/properties.html.nunj, libs/builder/templates/parts/member-remarks.html.nunj, libs/builder/templates/parts/remarks.html.nunj
Issue Number: #218 
Resolves #218
=> feat(builder): add support for `@remarks` tag

apps/ng-doc/docs/api-documentation/documenting-declarations/index.md, libs/app/styles/page.scss, libs/builder/engine/nunjucks/actions/api.action.ts, libs/builder/templates/api/base.html.nunj, libs/builder/templates/helpers/method.html.nunj, libs/builder/templates/helpers/overload.html.nunj, libs/builder/templates/helpers/properties.html.nunj, libs/builder/templates/parts/examples.html.nunj, libs/builder/templates/parts/member-examples.html.nunj
=> feat(builder): add support for `@example` tag

apps/ng-doc/docs/getting-started/configuration/index.md, libs/builder/helpers/repo-link.ts, libs/builder/interfaces/repo-config.ts, libs/builder/types/index.ts, libs/builder/types/supported-platforms.ts
Adds the ability to configure GitLab repos to work with "Suggest edits" and "View Source"
=> feat(builder): added support for gitlab repos

libs/app/package.json, package-lock.json, package.json
=> fix(package): bump version of Mermaid to 10.9.3

libs/ui-kit/components/expander/expander.component.scss
=> fix: items inside collapsed expander were clickable
